apiVersion: v1
kind: Service
metadata:
  name: spring-boot-kube-demo
spec:
  selector:
    app: spring-boot-kube-demo
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort